### ISSUE TITLE
Is it suitable for kernel version 4.19?

### ISSUE THREAD

**Issue by huaweihulk** [jeremyb31/ideapad-laptop#1]

**Comment by jeremyb31** [comment]
The 4.18 branch might compile on the 4.19 kernel, if it doesn't you could download and patch the 4.19 source code with https://github.com/jeremyb31/ideapad-laptop/commit/9c89a0c2121601f7975418a5b925d097f1984911

**Comment by huaweihulk** [comment]
I fix wifi with branch mater，Thank you for everything you have done！！My laptop work fine！！Thank you
